version: '3.8'

services:
  backend:
    build: ./backend
    container_name: aej_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=aejdb
    platform: linux/amd64 # Assurez-vous que l'architecture est compatible

  frontend:
    build: ./frontend  # Correctement indenté
    container_name: aej_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    platform: linux/amd64
    command: sh -c "npm install && npm run dev -- --host" # Assurez-vous que l'architecture est compatible

  mysql:
    image: mysql:5.7
    container_name: aej_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: aejdb
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dbdata:/var/lib/mysql
    platform: linux/amd64 # Assurez-vous que l'architecture est compatible

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: aej_phpmyadmin
    restart: always
    ports:
      - "8889:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    platform: linux/amd64 # Assurez-vous que l'architecture est compatible

volumes:
  dbdata:
